spring.application.name=notes
spring.datasource.url=postgresql://notes_db_qljx_user:HQCjBprivQ4UVIi0P0aDHNy4NAPv6SvP@dpg-d2socjmr433s73ft73gg-a.oregon-postgres.render.com/notes_db_qljx
spring.datasource.username=notes_db_qljx_user
spring.datasource.password=notes_db_qljx
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

